CREATE TABLE demo_employees (
    employee_id VARCHAR(50) PRIMARY KEY,
    login_id VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    department_name VARCHAR(100) NOT NULL,
    position_name VARCHAR(100),
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(30),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_demo_employees_login_id ON demo_employees (login_id);
CREATE UNIQUE INDEX uk_demo_employees_email ON demo_employees (email);
CREATE INDEX idx_demo_employees_phone_number ON demo_employees (phone_number);
CREATE INDEX idx_demo_employees_name ON demo_employees (name);

CREATE TABLE demo_annual_leave_balances (
    leave_balance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id VARCHAR(50) NOT NULL,
    leave_year INT NOT NULL,
    granted_days DECIMAL(5,2) NOT NULL DEFAULT 0,
    carried_over_days DECIMAL(5,2) NOT NULL DEFAULT 0,
    adjusted_days DECIMAL(5,2) NOT NULL DEFAULT 0,
    used_days DECIMAL(5,2) NOT NULL DEFAULT 0,
    scheduled_days DECIMAL(5,2) NOT NULL DEFAULT 0,
    pending_days DECIMAL(5,2) NOT NULL DEFAULT 0,
    expires_on DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_demo_leave_employee
        FOREIGN KEY (employee_id)
        REFERENCES demo_employees (employee_id),
    CONSTRAINT uk_demo_leave_employee_year
        UNIQUE (employee_id, leave_year)
);

INSERT INTO demo_employees (
    employee_id,
    login_id,
    name,
    department_name,
    position_name,
    email,
    phone_number,
    status
) VALUES
    ('202500061', 'mendel333', '고명진', '생보ITO1팀', '프로', 'mendel333@hanwha.com', '010-7658-7639', 'ACTIVE'),
    ('SA001', 'jinhyuk.kim', '김진혁', 'AI플랫폼팀', '매니저', 'jinhyuk.kim@hanwha.com', '010-1111-2222', 'ACTIVE');

INSERT INTO demo_annual_leave_balances (
    employee_id,
    leave_year,
    granted_days,
    carried_over_days,
    adjusted_days,
    used_days,
    scheduled_days,
    pending_days,
    expires_on
) VALUES
    ('202500061', 2026, 15.0, 1.0, 0.0, 4.0, 1.0, 0.5, DATE '2026-12-31'),
    ('SA001', 2026, 15.0, 0.0, 0.0, 2.0, 0.0, 0.0, DATE '2026-12-31');
